# Generated by Django 3.0.8 on 2020-07-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20200715_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeitnerBox',
            new_name='FlipBox',
        ),
        migrations.RenameField(
            model_name='scoreboard',
            old_name='leitner_date',
            new_name='Flip_date',
        ),
    ]
